### ISSUE TITLE
Prometheus scrape_config example fix

### ISSUE THREAD

**Issue by mcouillard** [ThePrez/prometheus-exporter-jdbc#13]
At least as of the current version of Prometheus, 2.42, you'll get an error if you include the path inside the `targets`.

Here's a working example:

`scrape_configs:`
`  - job_name: 'jdbc-exporter'`
`    metrics_path: '/metrics'`
`    static_configs:`
`      - targets: ['localhost:9853']`

**Comment by ThePrez** [comment]
Thanks for reporting! 
Does #14 look good to you?

**Comment by mcouillard** [comment]
Sure does, thank you!
