### ISSUE TITLE
Prometheus label usage?

### ISSUE THREAD

**Issue by mcouillard** [ThePrez/prometheus-exporter-jdbc#15]
First - I love what you've got here! I'm amazed there aren't many other ways to run simple queries that become metrics. Even the venerable Telegraf (of the TICK stack) doesn't have it.

Have you considered using a Prometheus Label for storing the Hostname instead of having it be the start of each key? If this were changed to a label it would support much easier Grafana charting across hosts. Today we have a handful of hosts that we'll be running this against. In Grafana we'll have to setup a static query for each unique hostname, unless a label is used where we can then make the chart group by this label, thus showing the label as part of the Chart Legend.

https://prometheus.io/docs/practices/naming/#labels

From:
`hostname123__QUERY_MEMPOOL_SIZE 44.4`

To:
`QUERY_MEMPOOL_SIZE{host="hostname123"} 44.4`

**Comment by ThePrez** [comment]
Thanks for the insight, @mcouillard! Your label change proposal seems like the right thing to do

**Comment by ThePrez** [comment]
@ajshedivy, can you take a peek?

**Comment by mcouillard** [comment]
...although, I'm seeing more clearly now that the 2 labels you do use, instance and job, could be leveraged for something similar.

In my example where multiple hosts are queried, we could just use the job name to describe each host. Then we'd disable the include_hostname so the keys are consistent across hosts.

Since a new job is required for each host anyway, this seems like a fine solution.

**Comment by ThePrez** [comment]
FWIW, I still would like to get around to addressing #6 some day, which would allow a single job to monitor multiple hosts. 

Regardless, the use of labels was, as a whole, not considered when building this tool, and they do bring some value when you get over to the visualization side of things. 

I'd propose the following actions: 
- Always add the "hostname" label to all metrics unconditionally
- Adding a "driver class" label to all metrics unconditionally (for those using JDBC to talk to other databases)
- keep the `include_hostname` logic as-is. If `include_hostname` is set to false, the hostname can still be gathered from the label 
- Add comments to issue #6 that we would need some logic to throw an error or ignore `include_hostname` if we're monitoring multiple hosts.

Sound acceptable?

**Comment by mcouillard** [comment]
I like that plan!
