### ISSUE TITLE
Newbie Issues

### ISSUE THREAD

**Issue by edshaw42** [ThePrez/prometheus-exporter-jdbc#23]
I was able to get it up and running, but since this is my first experience with Grafana, I cannot seem to obtain access to any data. I imagine I am just enter the setup incorrectly on Grafana. I was able to connect to my port and test and it says it has a connection but when I try  SYSTEMNAME__...... in the config for a dashboard I never have success. 

Any help, screenshots, or tips would be appreciated, I think I am soooo close!

**Comment by ThePrez** [comment]
Greetings. 
You may have started with my article [here](https://techchannel.com/Trends/12/2022/ibm-i-prometheus), but linking just in case. 

Are you able to see the metrics of interest in Prometheus? You can search in the "expression" field of the main web view. 
![image](https://user-images.githubusercontent.com/17914061/232349830-91fbffac-c4d1-41d6-8e42-e628866eb472.png)
