### ISSUE TITLE
Question about "Any numeric metric available through SQL can be monitored using this client!"

### ISSUE THREAD

**Issue by AverittLogan** [ThePrez/prometheus-exporter-jdbc#37]
I am wondering about this line from the README. Please forgive my ignorance on Prometheus, any info on this topic is appreciated!

"Any numeric metric available through SQL can be monitored using this client!"

We are currently trying to capture and display text/character/string data types using Prometheus. (Our use case is to get the fully qualified names of the top X jobs {job_num/user/jobname} ). Is it only possible to capture numeric data? If so, why is that? Is there any alternative way to get text information.

Thank you,
Logan

**Comment by krka01** [comment]
The Prometheus backend does not support non-numeric values.

For the task you try to accomplish, Prometheus is not the way to go.  

One solution would be use the QSYS2.ACTIVE_JOB_INFO() table function and forward the data to ELK, Splunk or other syslog server that support building graphs.

Another solution would be to use LPAR2RRD and the IBM i OS Agent, but you would need to setup an LPAR2RRD server on AIX or Linux: https://lpar2rrd.com/as400.php#as400-docu

**Comment by AverittLogan** [comment]
thanks @krka01
